### ISSUE TITLE
Logo design for chatter

### ISSUE THREAD

**Issue by harunbadilli** [audaniel9/Chatter#4]
I have designed a logo for you and I want to give you a present. You can review the details from the pictures below. You're free to choose what you want. everything is for you. I hope you like it

![1](https://user-images.githubusercontent.com/34319922/40580410-349bcc0e-6146-11e8-8920-73eb110c9d55.png)
![2](https://user-images.githubusercontent.com/34319922/40580411-34c5eb7e-6146-11e8-99ce-9792c59c2583.png)
![3](https://user-images.githubusercontent.com/34319922/40580412-34efc156-6146-11e8-9a47-1340d2af738d.png)

**Comment by audaniel9** [comment]
Thanks for the contribution.
